### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined ?

### ISSUE THREAD

**Issue by ghost** [linq2js/linq2fire#10]
**After I using**
**Ts**
` ...(this.data.amenitiesList ? { or: this.data.amenitiesList.map(amenityItem => ({ 'amenitiesList array-contains': amenityItem })) } : undefined),`

**Console:** 
`TypeError: Cannot read property 'type' of undefined`
I try to defined all variables and same problem . what can I do ?

```
data = {
amenitiesList = [];
}
```
**After Removing** 
` ...(this.data.amenitiesList ? { or: this.data.amenitiesList.map(amenityItem => ({ 'amenitiesList array-contains': amenityItem })) } : undefined),`

**Console:**
No any error :(

**Comment by linq2js** [comment]
You need to give me more clue: more code lines (10 lines around the line getting error), stack trace,  value of values "this.data", "this.data.amenitiesList"

**Comment by ghost** [comment]
**Ts get data of HTML5**

```
data = {
    cityList: '',
    areaList: '',
    propertyList: '',
    minPrice: '',
    maxPrice: '',
    bedroomList: '',
    bathroomList: '',
    floorList: '',
    ageList: '',
    postList: '',
    furnishList: '',
    rentalList: '',
    amenitiesList: [],
    livingRoom: '',
    maidRoom: '',
    guestRoom: '',
  };
```

**Ts FacetFilter**
```
 const result = linq(db).where({
      ...(this.data.areaList ? { 'areaList ==': this.data.areaList } : undefined),
      ...(this.data.propertyList ? { 'propertyList ==': this.data.propertyList } : undefined),
      ...(this.data.minPrice ? { 'price >=': Number(this.data.minPrice) } : undefined),
      ...(this.data.maxPrice ? { 'price <=': Number(this.data.maxPrice) } : undefined),
      ...(this.data.bedroomList ? { 'bedrooms ==': this.data.bedroomList } : undefined),
      ...(this.data.bathroomList ? { 'bathrooms ==': this.data.bathroomList } : undefined),
      ...(this.data.floorList ? { 'floorList ==': this.data.floorList } : undefined),
      ...(this.data.ageList ? { 'ageList ==': this.data.ageList } : undefined),
      ...(this.data.postList ? { 'postList ==': this.data.postList } : undefined),
      ...(this.data.furnishList ? { 'furnishList ==': this.data.furnishList } : undefined),
      ...(this.data.rentalList ? { 'rentalList ==': this.data.rentalList } : undefined),
      // tslint:disable-next-line:max-line-length
      ...(this.data.amenitiesList ? { or: this.data.amenitiesList.map(amenityItem => ({ 'amenitiesList array-contains': amenityItem })) } : undefined),
      ...(this.data.livingRoom ? { 'livingroom ==': this.data.livingRoom } : undefined),
      ...(this.data.maidRoom ? { 'maidroom ==': this.data.maidRoom } : undefined),
      ...(this.data.guestRoom ? { 'guestroom ==': this.data.guestRoom } : undefined),

    }).get().then(printDocs('Find all tasks which starts with Task')).catch(error => console.log(error));
```

**Comment by ghost** [comment]
Can I change undefined to null ?

**Comment by ghost** [comment]
Help please

**Comment by ghost** [comment]
My problem in **or:** `this.data.amenitiesList.map(amenityItem => ({ 'amenitiesList array-contains': amenityItem })) } : undefined),`

**Comment by linq2js** [comment]
@Omar-Qalei I see but I cannot guess what happened, could you show stack trace of error ? or debug step by step and show where error occurs

**Comment by ghost** [comment]
After adding 
`...(this.data.amenitiesList ? { or: this.data.amenitiesList.map(amenityItem => ({ 'amenitiesList array-contains': amenityItem })) } : undefined),`
Console:
```
ERROR TypeError: Cannot read property 'type' of undefined
    at index.js:102
    at traverse (index.js:76)
    at index.js:79
    at Array.some (<anonymous>)
    at traverse (index.js:78)
    at index.js:79
    at Array.some (<anonymous>)
    at traverse (index.js:78)
    at findAllPossibles (index.js:101)
    at buildQueries (index.js:332)
```

**Comment by linq2js** [comment]
I tried to duplicate your case https://codesandbox.io/s/zrr31085l3 but nothing happen
Please refactor your code like this:
const condition = { ... }
console.log(JSON.stringify(condition));
const result = linq(db).where(condition);

and give me full JSON text of condition variable

**Comment by ghost** [comment]
Can you give me full example

**Comment by linq2js** [comment]
const condition = {
      ...(this.data.areaList ? { 'areaList ==': this.data.areaList } : undefined),
      ...(this.data.propertyList ? { 'propertyList ==': this.data.propertyList } : undefined),
      ...(this.data.minPrice ? { 'price >=': Number(this.data.minPrice) } : undefined),
      ...(this.data.maxPrice ? { 'price <=': Number(this.data.maxPrice) } : undefined),
      ...(this.data.bedroomList ? { 'bedrooms ==': this.data.bedroomList } : undefined),
      ...(this.data.bathroomList ? { 'bathrooms ==': this.data.bathroomList } : undefined),
      ...(this.data.floorList ? { 'floorList ==': this.data.floorList } : undefined),
      ...(this.data.ageList ? { 'ageList ==': this.data.ageList } : undefined),
      ...(this.data.postList ? { 'postList ==': this.data.postList } : undefined),
      ...(this.data.furnishList ? { 'furnishList ==': this.data.furnishList } : undefined),
      ...(this.data.rentalList ? { 'rentalList ==': this.data.rentalList } : undefined),
      // tslint:disable-next-line:max-line-length
      ...(this.data.amenitiesList ? { or: this.data.amenitiesList.map(amenityItem => ({ 'amenitiesList array-contains': amenityItem })) } : undefined),
      ...(this.data.livingRoom ? { 'livingroom ==': this.data.livingRoom } : undefined),
      ...(this.data.maidRoom ? { 'maidroom ==': this.data.maidRoom } : undefined),
      ...(this.data.guestRoom ? { 'guestroom ==': this.data.guestRoom } : undefined),

    };

**Comment by ghost** [comment]
JSON:
`
{"areaList ==":["Aanjara"],"or":[]}`

**Comment by ghost** [comment]
JSON MORE THAN 2 SELECTED
`{"areaList ==":["Aanjara"],"propertyList ==":["PROPERTY_LIST.STUDIO"],"or":[]}`

**Comment by linq2js** [comment]
why or criteria is empty, please add more critera (this.data.amenitiesList && this.data.amenitiesList.length) ? .. : .. 
 to eliminate empty or case

**Comment by ghost** [comment]
What do you mean?

**Comment by linq2js** [comment]
The original code is
...(this.data.amenitiesList ? { or: this.data.amenitiesList.map(amenityItem => ({ 'amenitiesList array-contains': amenityItem })) } : undefined),

please refactor to: 
...(this.data.amenitiesList && this.data.amenitiesList.length ? { or: this.data.amenitiesList.map(amenityItem => ({ 'amenitiesList array-contains': amenityItem })) } : undefined),

new code version can eliminate the case: amenitiesList is not undefined but it has not item, so no empty OR criteria will be generated

**Comment by ghost** [comment]
After refactoring no data output
only this
`********** FIND ALL TASKS WHICH STARTS WITH TASK **********`

**Comment by ghost** [comment]
I was selecting more than one and didn't show any data

**Comment by linq2js** [comment]
{"areaList ==":["Aanjara"],"propertyList ==":["PROPERTY_LIST.STUDIO"]}
is there any data satisfied this criteria ?

**Comment by ghost** [comment]
No, I talk about `this.data.amenitiesList`

**Comment by ghost** [comment]
**After selecting** 

`{"or":[{"amenitiesList array-contains":"AMENITIES_LIST.AIR_CONDITIONING"}]}`

**Output**

`********** FIND ALL TASKS WHICH STARTS WITH TASK **********`

**Comment by linq2js** [comment]
check your db, and make sure there is at least record has amenitiesList which contains AMENITIES_LIST.AIR_CONDITIONING

**Comment by ghost** [comment]
I checked

**Comment by linq2js** [comment]
and what result ?

**Comment by ghost** [comment]
**After selecting**

`{"or":[{"amenitiesList array-contains":"AMENITIES_LIST.AIR_CONDITIONING"}]}`

**Output**

`********** FIND ALL TASKS WHICH STARTS WITH TASK **********`

**Comment by ghost** [comment]
Please I will stop this Issue talk tomorrow , thanks for helped .

**Comment by linq2js** [comment]
I mean you must verify your db records, if the result is empty that means there is not any record satisfied criteria

**Comment by ghost** [comment]
I will check tomorrow.
