### ISSUE TITLE
array-contains and In operator together

### ISSUE THREAD

**Issue by jassiwaliaVC** [linq2js/linq2fire#13]
Hi can  we use array-contains and in operatopr together like this

link(db).collection(tbl).where({'mobile array-contains': ['21389213', '231123213']}).data();

**Comment by jassiwalia001** [comment]
@linq2js can u please looki into this and tell me the correct approach

**Comment by linq2js** [comment]
you can do this:
```
const values = ['21389213', '231123213'];
linq(db.collection(tbl)).where({
  or: values.map(value => ({
     'mobile array-contains': value
  }))
})
```

**Comment by jassiwalia001** [comment]
@linq2js what if i have to add multiple OR conditions like this 
`
const values = ['21389213', '231123213'];
const id= ['12', '43'];

linq(db.collection(tbl)).where({
  or: [values.map(value => ({
     'mobile array-contains': value
  })), id.map(id=> ({
     'id array-contains': id
  }))]
})
`

**Comment by jassiwalia001** [comment]
@linq2js please assist with this as i have URGENT lookup

**Comment by linq2js** [comment]
You can write down many OR, so what is result ? does it work ?

**Comment by jassiwalia001** [comment]
no it gave me empty array. which is not correct. is any other approach or work arround to do this can you check this

**Comment by linq2js** [comment]
could you show me some pies of your data ?

**Comment by jassiwalia001** [comment]
@linq2js 
This is my data json array

`[
  {
    "name": "Jassi",
    "id": [
      "1",
      "2",
      "3"
    ],
    "mobile": [
      "919041356231",
      "919780412223"
    ]
  },
  {
    "name": "Walia",
    "id": [
      "123",
      "456",
      "789"
    ],
    "mobile": [
      "919041356231",
      "919780412223"
    ]
  },
  {
    "name": "Jassi",
    "id": [
      "321",
      "654",
      "987"
    ],
    "mobile": [
      "919041356231",
      "919780412223"
    ]
  }
]`

and 

this is my linq 2 implementation

``
const values = ['919041356231', '231123213'];
const id= ['123', '43'];

linq(db.collection(tbl)).where({
or: [values.map(value => ({
'mobile array-contains': value
})), id.map(id=> ({
'id array-contains': id
}))]
})`

**Comment by linq2js** [comment]
ah, I know why your implement does not work, or requires array of condition, but, you passed array of array condition, it should be
```
linq(db.collection(tbl)).where({
or: [...values.map(value => ({
'mobile array-contains': value
})), ...id.map(id=> ({
'id array-contains': id
}))]
})
```

**Comment by jassiwaliaVC** [comment]
wow wow you just made my day thanks a lot you are awsm man
