### ISSUE TITLE
Feature Request: Find by @id NOT IN 

### ISSUE THREAD

**Issue by ghost** [linq2js/linq2fire#16]
Is this already possible?

Current problem:
```
let db = await linq(admin.firestore()).from('collection')
await db.where({
    '@id !=': ['abcd', 'efgh', 'lmno'],
    'gender': ['male', 'other']
}).limit(10).get().then(...)
```

Error: 
`Unhandled error Error: Invalid criteria @id !=`

thanks

**Comment by ghost** [comment]
Ok just realised this is because I was using `1.0.20` instead of `1.0.21`.

I would mention that `1.0.21` is not yet available via npm so I had to clone this repo.

This issue can be closed thanks again :+1:

**Comment by ghost** [comment]
EDIT: for some reason `@id !=` is not working, however use `@id<>` and everything is fine!

**Comment by linq2js** [comment]
It seems there is space between @id and !=
