### ISSUE TITLE
Feature request: Array contains x AND y

### ISSUE THREAD

**Issue by ghost** [linq2js/linq2fire#17]
Pretty sure this isn't possible, would like to know if you could think of any work arounds without having to restructure all of my data.

Im my firestore have a document that holds an array:
`users: ['user1Id', 'user2Id']`

I would like to query for all documents where users contains 'user1Id' AND contains 'user2Id'.

List of things I have tried: 
```
where({
    'users has': ['user1Id', 'user2Id']
})
```

```
where({
    or: {
        'users': ['user1Id', 'user2Id'],
        'users': ['user2Id', 'user1Id'],
    }
})
```

```
where({
    'users has': ['user1Id'],
    'users has': ['user2Id']
})
```
^ this has duplicate object key, so will not work

so i thought i'd be cheeky and try this
```
where({
    'users has': ['user1Id'],
    'users array-contains': ['user2Id']
})
```
however.. `A maximum of 1 'ARRAY_CONTAINS' filter is allowed`

Again any advice or help is muchly appreciated! :+1:

**Comment by linq2js** [comment]
I have just published a new version, that contains query criteria improvement. Now has operator works with Array as you described
