### ISSUE TITLE
[Android] Can't find variable: Symbol

### ISSUE THREAD

**Issue by phuongpt** [linq2js/linq2fire#4]
![screen shot 2018-08-06 at 6 26 05 pm](https://user-images.githubusercontent.com/4443583/43714593-b3377cd6-99a7-11e8-8094-63793686178e.png)

**Comment by linq2js** [comment]
@phuongpt 
so strange, Symbol is supported by modern browsers and mobile platform, seems like nothing relates to my lib

**Comment by phuongpt** [comment]
I'm not sure, it worked well on version 1.0.6

**Comment by linq2js** [comment]
ok let me remove all Symbol usages in my lib, hopefully that helps

**Comment by phuongpt** [comment]
@linq2js confirm it works

**Comment by linq2js** [comment]
@phuongpt I just shipped new package it called immhelper, a helper lib for immutable js objects. feel free to use it ? https://github.com/linq2js/immhelper
