### ISSUE TITLE
type.d.ts for linq2fire

### ISSUE THREAD

**Issue by pdemilly** [linq2js/linq2fire#5]
Would love to have one for proper usage

**Comment by linq2js** [comment]
sure, let me provide

**Comment by linq2js** [comment]
@pdemilly added in https://github.com/linq2js/linq2fire/commit/045a211575999eadd2426fe9ebb153c522f383bb#diff-b52768974e6bc0faccb7d4b75b162c99

**Comment by pdemilly** [comment]
Could you provide an example in transcript. Because it is not working for me
