### ISSUE TITLE
Support array_contains?

### ISSUE THREAD

**Issue by phuongpt** [linq2js/linq2fire#6]
Hello @linq2js 
My structure in FireStore looks like this:
```
published: true
tags:{
"textA": true,
"textB": true
}
```
When I want to create query like this
```
.where({
                'published ==': false,
                'tags.textA ==': true
              })
```
It requires index for `published` and `tags.textA` manually. So I have to change my structure to 
```
published: true
tags:['textA', 'textB']
```
But I need something like `array-contains`, how do you thing about this issue?

**Comment by linq2js** [comment]
@phuongpt I added array_contains operator, https://firebase.google.com/support/release-notes/js

**Comment by phuongpt** [comment]
cool @linq2js how can I use it in your plugin? I got issue `Error: Invalid criteria tags 'array-contains'`

**Comment by linq2js** [comment]
Just update the typo (array_contains -> array-contains) fixing. Test here https://codesandbox.io/s/zrr31085l3

**Comment by linq2js** [comment]
@phuongpt please update linq2js to latest

**Comment by linq2js** [comment]
@phuongpt I also added 'has' operator which is shorthand of array-contains

**Comment by phuongpt** [comment]
I see @linq2js  👍

**Comment by phuongpt** [comment]
@linq2js how do you think about array `containedIn` array operator?

**Comment by linq2js** [comment]
@phuongpt please describe use case

**Comment by phuongpt** [comment]
for example, I have an article which is targeted to groups [A, B]. And my account is able to see articles in groups [A, C]. So I should see this article.

**Comment by linq2js** [comment]
here is my skype linqtojs, ping me if you have time to discuss
