### ISSUE TITLE
Debug linq is not defined in Angular 6 + Linq2Fire?

### ISSUE THREAD

**Issue by ghost** [linq2js/linq2fire#7]
**My code:**
https://codesandbox.io/s/20ml7xvz3r

**Note: After installed Linq2Fire and use linq method show this error.**

**Console Error:**
https://scontent.famm6-1.fna.fbcdn.net/v/t1.0-9/42959644_742373419432961_2433364256134004736_n.jpg?_nc_cat=102&oh=a8f19ad7536331b0360c5a50385d2e19&oe=5C17BCFE

**Comment by ghost** [comment]
@linq2js  I found my problem how can I compare data  of Firestore with my selected ?

**Comment by ghost** [comment]
@linq2js
this your code 
```
 const ref = this.afs.collection('AddListDataForRent');
    const result = linq(ref).where({
     ...(this.data.areaList ? {  name: this.data.areaList } : undefined),
     ...(this.data.propertyList ? {  areaList: this.data.propertyList } : undefined),
      }).get();
```
this my code : 
```
let query: firebase.firestore.Query | firebase.firestore.CollectionReference = list ;

    for (let _i = 0; _i < this.data.areaList.length; _i++) {
      if (this.data.areaList[_i]) { query = query.where('areaList', '==', this.data.areaList[_i.toString()]); }
    }

 for (let _j = 0; _j < this.data.propertyList.length; _j++) {

         if (this.data.propertyList[_j]) { query = query.where('propertyList', '==', this.data.propertyList[_j]); }
           }
```

**Comment by ghost** [comment]
@linq2js
CMD: error
https://scontent.famm6-1.fna.fbcdn.net/v/t1.0-9/43022901_742395192764117_5161344177643978752_o.jpg?_nc_cat=102&oh=995d131502d03bc82bfca6070e37c05d&oe=5C53EAF6

**Comment by linq2js** [comment]
@Omar-Qalei is this solved ?

**Comment by ghost** [comment]
@linq2js 
linq2fire work 100% on Angular 6 no problem I think my problem yesterday my laptop need restart only 👍  .
