### ISSUE TITLE
How can I compare data of Firestore with data of object ?

### ISSUE THREAD

**Issue by ghost** [linq2js/linq2fire#8]
Firestore  
https://scontent.famm6-1.fna.fbcdn.net/v/t1.0-9/42982662_742548456082124_4206794649660030976_o.jpg?_nc_cat=107&oh=6097654c6ac4598320a8eff8e4106aad&oe=5C555DDD

```
const printDocs = heading => docs => {
      console.log('**********', heading.toUpperCase(), '**********');
      docs.forEach(doc => console.log(doc.id, doc.data()));
      console.log();
    };

    const ref = this.afs.collection('AddListDataForRent');
    const result = linq(ref).where({
     ...(this.data.areaList ? {  'areaList ===': this.data.areaList } : undefined),
     ...(this.data.propertyList ? {  'propertyList ===': this.data.propertyList } : undefined),
      }).get().then(printDocs('Find all tasks which starts with Task'));
    

```
After comparing 

I can't use (spread operator)
Console Error:
https://scontent.famm6-1.fna.fbcdn.net/v/t1.0-9/43003326_742548432748793_1110203519362662400_o.jpg?_nc_cat=108&oh=c14ebe301e6056017f64d0b703933aaf&oe=5C229C26

**Comment by linq2js** [comment]
what type of this.data.areaList and this.data.propertyList ?
are they array or primitive type (string, number, boolean) ?

**Comment by ghost** [comment]
I solved my problem use:
```
const db = firebase.firestore().collection('AddListDataForRent');
const result = linq(db).where({
     ...(this.data.areaList ? {  'areaList ==': this.data.areaList.toString() } : undefined),
     ...(this.data.propertyList ? {  'propertyList ==': this.data.propertyList.toString()  } : undefined),
      }).get().then(printDocs('Find all tasks which starts with Task'));
```

**Comment by ghost** [comment]
@linq2js  you didn't tell me use 
`const db = firebase.firestore().collection('AddListDataForRent');`

**Comment by ghost** [comment]
@linq2js  but I can't use 
 `=== ` 3 equivalent  only 2 `==`

**Comment by ghost** [comment]
Thank you very much and Thank you for your efforts  .
I like you 👍

**Comment by linq2js** [comment]
@Omar-Qalei  by default areaList: xxx => 'areaList==': xxx
